### ISSUE TITLE
nannyml can confuse months with days on some rows of a dataset

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#104]
**Describe the bug**
NannyML gets the month and the date values wrong and can make a date of 01-09-2018 (1st September 2018) be thought of 09-01-2018 (9th January 2018).

**To Reproduce**
Install NannyML and run the following code in a jupyter notebook:

```
import wget
from pathlib import Path
import pandas as pd
import nannyml as nml


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00618/Steel_industry_data.csv'
download_foler = Path.home().joinpath("Downloads")
filename = wget.download(url,out = str(download_foler))

data = pd.read_csv(filename, header=0)
display(data.head())

features_selected = list(data.columns)[2:]

data['partition'] = 'train'
ind_ = data.shape[0]//3
data.loc[ind_:2*ind_, 'partition'] = 'reference'
data.loc[2*ind_: , 'partition'] = 'analysis'

reference = data.loc[data.partition == 'reference', :].reset_index(drop=True)
analysis = data.loc[data.partition == 'analysis', :].reset_index(drop=True)

calc = nml.UnivariateStatisticalDriftCalculator(
    feature_column_names=[features_selected[0]],
    timestamp_column_name='date'
)
calc.fit(reference)
results = calc.calculate(analysis)

drift_fig = results.plot(kind='feature_drift', feature_column_name=features_selected[0], plot_reference=True)
drift_fig.show()

display(results.data)
display(analysis)

```

A partial screenshot of the `results.data` can be seen below:

![Screenshot 2022-08-30 at 15-28-31 NP18 UCI Ste… (2) - JupyterLab](https://user-images.githubusercontent.com/89025229/187436719-242d279d-8565-4e44-a748-ad19de6e2adb.png)

A partial screensgot of the first and last line of the analysis dataframe can be seen below:

![Screenshot 2022-08-30 at 15-27-04 NP18 UCI Ste… (2) - JupyterLab](https://user-images.githubusercontent.com/89025229/187436803-a403f3f3-ae79-4a4f-9e26-89fa503fe203.png)

By comparing the two screenshots you can see that some dates have been altered.

**Expected behavior**
The dates would be recognized correctly. The misidentification of dates can be seen by comparing the start and end dates of the results data and the start and end dates of the analysis dataset.

**Screenshots & scripts**
The problem is also visible on the following univariate drift plot:

![newplot(24)](https://user-images.githubusercontent.com/89025229/187435771-d5632f1c-2398-4c91-b7f6-813f485ce139.png)

**Comment by jakubnml** [comment]
Apart from issues mentioned here keep in mind there might be issues coming from naive datetimes (without time zones). In extreme cases for high frequency data when someone wants to have hourly chanks this can generate problems when the time changes (we will have the same hour twice or one hour of data will be missing).

**Comment by nnansters** [comment]
Hey,

it seems like the date format in the data was a bit too exotic to be parsed correctly. 

If I manually parse the timestamps during preprocessing like `data['date'] = pd.to_datetime(data['date'], format='%d/%m/%Y %H:%M')`, I end up with the following plot:

![newplot(3)](https://user-images.githubusercontent.com/94110348/188008725-addf03f8-c821-481c-ac3b-4b6b3ecd6737.png)

The question is if we consider this to be a part of the data requirements, as currently [documented](https://nannyml.readthedocs.io/en/stable/tutorials/data_requirements.html#timestamp) or provide some options in the library to deal with this? I'd lean towards the first.

**Comment by nnansters** [comment]
Hey,

it seems like the date format in the data was a bit too exotic to be parsed correctly. 

If I manually parse the timestamps during preprocessing like `data['date'] = pd.to_datetime(data['date'], format='%d/%m/%Y %H:%M')`, I end up with the following plot:

![newplot(3)](https://user-images.githubusercontent.com/94110348/188008725-addf03f8-c821-481c-ac3b-4b6b3ecd6737.png)

The question is if we consider this to be a part of the data requirements, as currently [documented](https://nannyml.readthedocs.io/en/stable/tutorials/data_requirements.html#timestamp) or provide some options in the library to deal with this? I'd lean towards the first.

**Comment by nikml** [comment]
Issue still reproducible under the latest version

```
import wget
from pathlib import Path
import pandas as pd
import nannyml as nml


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00618/Steel_industry_data.csv'
download_foler = Path.home().joinpath("Downloads")
filename = wget.download(url,out = str(download_foler))

data = pd.read_csv(filename, header=0)
display(data.head())

features_selected = list(data.columns)[2:]

data['partition'] = 'train'
ind_ = data.shape[0]//3
data.loc[ind_:2*ind_, 'partition'] = 'reference'
data.loc[2*ind_: , 'partition'] = 'analysis'

reference = data.loc[data.partition == 'reference', :].reset_index(drop=True)
analysis = data.loc[data.partition == 'analysis', :].reset_index(drop=True)

calc = nml.UnivariateDriftCalculator(
    column_names=[features_selected[0]],
    timestamp_column_name='date',
    continuous_methods=['kolmogorov_smirnov',],
    categorical_methods=['chi2']
)
calc.fit(reference)
results = calc.calculate(analysis)

drift_fig = results.plot(kind='drift', column_name=features_selected[0], method='kolmogorov_smirnov', plot_reference=True)
drift_fig.show()

display(results.data)
display(analysis)
```

**and date fix as suggested successfully resolves the issue**

```
import wget
from pathlib import Path
import pandas as pd
import nannyml as nml


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00618/Steel_industry_data.csv'
download_foler = Path.home().joinpath("Downloads")
filename = wget.download(url,out = str(download_foler))

data = pd.read_csv(filename, header=0)
display(data.head())

features_selected = list(data.columns)[2:]

data['partition'] = 'train'
ind_ = data.shape[0]//3
data.loc[ind_:2*ind_, 'partition'] = 'reference'
data.loc[2*ind_: , 'partition'] = 'analysis'

# date fix
data['date'] = pd.to_datetime(data['date'], format='%d/%m/%Y %H:%M')

reference = data.loc[data.partition == 'reference', :].reset_index(drop=True)
analysis = data.loc[data.partition == 'analysis', :].reset_index(drop=True)

calc = nml.UnivariateDriftCalculator(
    column_names=[features_selected[0]],
    timestamp_column_name='date',
    continuous_methods=['kolmogorov_smirnov',],
    categorical_methods=['chi2']
)
calc.fit(reference)
results = calc.calculate(analysis)

drift_fig = results.plot(kind='drift', column_name=features_selected[0], method='kolmogorov_smirnov', plot_reference=True)
drift_fig.show()

display(results.data)
display(analysis)
```
