### ISSUE TITLE
Conda Forge

### ISSUE THREAD

**Issue by thewchan** [NannyML/nannyml#107]
Hello! I have successfully put this package on to Conda Forge, and I am extending the invitation for the owner/maintainers of this package to be maintainers on Conda Forge as well. Let me know if you are interested! Thanks.
https://github.com/conda-forge/nannyml-feedstock

**Comment by nnansters** [comment]
Hey Matt, thanks for the reminder. I've created the appropriate issue on the feedstock repository following the guidelines. Happily awaiting your merge.

Not 100% sure when I'll have to intervene manually in the process, I'll give the docs another proper reading.

**Comment by thewchan** [comment]
@nnansters Thanks! I basically whenever an update is made upstream in PyPI, the bots will make a PR to update in conda as well. If all tests pass when we can just merge the PR. Else, sometimes we do need to modify the YAML recipe, usually to update the dependencies etc., but should all be pretty straightforward. 

Thanks again!
