### ISSUE TITLE
Reader base class uses `WriterException` to handle _read() failure

### ISSUE THREAD

**Issue by baskervilski** [NannyML/nannyml#109]
**Describe the bug**
I know it's nitpicking, but just noticed this in `nannyml.io.base`, within the `Reader` class, `read()` method:
https://github.com/NannyML/nannyml/blob/8dbc6bf1c7c983f421795ad4d11f3ea26d12dba1/nannyml/io/base.py#L67

I guess the impact is minimal, apart from it being an eyesore. I could maybe do a PR myself to add the `ReaderException` and use it here.

**Expected behavior**
Reader exceptions should be handled with `ReaderExceptions`. :-)

**Comment by nnansters** [comment]
Haha, fair is fair. Thanks for reporting. We'll get it fixed by next release!

**Comment by nnansters** [comment]
Or as you suggested, a PR is always welcome! Let me know if you want to take on this daunting task, otherwise I'll put it on my own to-do list.

**Comment by baskervilski** [comment]
If you agree that the solution is to just create the `ReaderException` class and use it in the abovementioned line, then sure, let me have it. :-)
