### ISSUE TITLE
Speed-up tox env setup using skip_install=true

### ISSUE THREAD

**Issue by baskervilski** [NannyML/nannyml#111]
Another low-impact improvement proposal from my side. :-)

### Description

As I can see in [setup.cfg](https://github.com/NannyML/nannyml/blob/c8deac9e7c3640f5b4c254ef08aba9aa7893e62b/setup.cfg) (unless I'm missing something) the `format`, `lint` and `build` tox env specifications don't have the `skip_install=true` option in their configuration, which will unnecessarily install the `nannyml` package in each of these envs (and at each run, not only on env recreation), making the env run time unnecessarily longer.

https://tox.wiki/en/latest/config.html?force_isolation=true#conf-skip_install

### Proposed solution

Adding `skip_install=true` to `format`, `lint` and `build` tox env specifications in `tox.ini`

**Comment by nnansters** [comment]
Good idea, hadn't thought about it yet :raised_hands: . Feel free to pop in another PR if you're up for it!
