### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'model_metadata'

### ISSUE THREAD

**Issue by ai-noahdolev** [NannyML/nannyml#114]
Hi,

The example fails to run. 
```
reference_df, analysis_df, target_df = nml.load_synthetic_binary_classification_dataset()

estimator = nml.CBPE(
    y_true='work_home_actual',
    y_pred='y_pred',
    y_pred_proba='y_pred_proba',
    timestamp_column_name='timestamp',
    metrics=['f1', 'roc_auc'],
    problem_type='classification_binary',
)

estimator.fit(reference_df)
```

Gives the error in the title `TypeError: __new__() missing 1 required positional argument: 'model_metadata'`

**Comment by nnansters** [comment]
Hey @ai-noahdolev, that seems to be a very old version of the library you're running there. In that case you'll have to find the matching version of the documentation but I strongly recommend making sure you're on the latest version. 

Can you verify the version of NannyML using `pip list | grep nannyml` in your terminal?
