### ISSUE TITLE
Add bootstrapping options to chunk methods

### ISSUE THREAD

**Issue by ai-noahdolev** [NannyML/nannyml#117]
It would be nice if you'd allow bootstrapping (resampling with replacement) instead of non-overlapping chunks for the CBPE estimate.  Ideally, something like this:
https://stats.stackexchange.com/questions/96739/what-is-the-632-rule-in-bootstrapping

**Comment by nnansters** [comment]
Hey Noah, 

thanks for the pointer! How do you envision the bootstrapping to fit within the library? As a replacement for the chunking, as something to perform on each chunk after splitting, ... ?

We've already identified that chunking is not always the best way to proceed and are definitely interested in checking out some alternatives.

**Comment by ai-noahdolev** [comment]
I would suggest that you simply expand the chunking engine to support bootstrapping for a start. E.g., the analysis you collect on a chunk you now collect on a bootstrap subsample. As a first step, maybe consider using numpy.random.Generator.choice to create your chunk?

**Comment by nnansters** [comment]
Ah yes, I see. Instead of just splitting a dataset into non-overlapping chunks (like you've mentioned) you would take that dataset as a whole and generate chunks of a fixed size by performing bootstrapping on it? 

Seems like a low-effort thing to try out indeed.

@nikml any thoughts on this?

**Comment by nikml** [comment]
I m hesitant because I m not sure about the use case. Because supporting that further into the pipeline, meaning creating results and then creating a plot out of them looks tricky.

- Maybe it will be simpler after we remove timestamps?
- Also, maybe the ability to perform CBPE on analysis data as a whole would help (assuming the user does the sampling) ?

Do you mind sharing a little bit more around how you would use that functionality @ai-noahdolev ?

**Comment by ai-noahdolev** [comment]
Hi,

The use case would be testing a model on yet unforeseen data.  The problem is, in cases where there is not a lot of sample data (and/or "analysis" data), the chunking process (which is essentially subsampling without replacement) is too conservative (e.g., you can't create enough chunks to tell you something interesting about the "analysis" data).   Instead of estimating the metric within a chunk, you could just as easily estimate inside a bootstrap subsample. 

With regard to time - it would certainly be simpler without timestamps. But even with time stamps, you can subsample and take the mean "time" as the centroid for that subsample when plotting. This is essentially a smoothing filter for the time plot but it would allow you a more nuanced measure of confidence at each time point (e.g., large, sudden changes would have larger confidence bounds/less certainty)...

**Comment by nnansters** [comment]
Original data reconstruction error with `SizeBasedChunker(size=5000)`:

![image](https://user-images.githubusercontent.com/94110348/193574494-937d2d93-19ea-44ce-97b9-0c35e7af4a6c.png)

Same data and calculator, `BootstrapChunker(chunk_count=10, n=5000)
`
![image](https://user-images.githubusercontent.com/94110348/193574688-c1fe50e6-e31c-4a98-bb59-f8f566b8f712.png)

`BootstrapChunker(chunk_count=20, chunk_count=10000)`

![image](https://user-images.githubusercontent.com/94110348/193574825-da710807-8fa8-40ca-83e2-8d3f261cfa40.png)

`BootstrapChunker(chunk_count=30, chunk_count=10000)`

![image](https://user-images.githubusercontent.com/94110348/193574915-4e806d7d-86ba-4cb3-a335-f910a7dc2ebd.png)
