### ISSUE TITLE
Specifying chunk_count on realized performance causes dates to be ignored in plots and results

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#129]
**Describe the bug**
When using chunk_count as a chunker option in realized performance dates are ignored in results and plots.

**To Reproduce**
The results are reproduced with the following code:

```
import pandas as pd
import nannyml as nml
from IPython.display import display

reference_df = nml.load_synthetic_car_price_dataset()[0]
analysis_df = nml.load_synthetic_car_price_dataset()[1]
analysis_target_df = nml.load_synthetic_car_price_dataset()[2]
analysis_df = analysis_df.join(analysis_target_df)

display(reference_df.head(3))

calc = nml.PerformanceCalculator(
    y_pred='y_pred',
    y_true='y_true',
    timestamp_column_name='timestamp',
    problem_type='regression',
    metrics=['rmse', ],
    chunk_number=10)

calc.fit(reference_df)

results = calc.calculate(analysis_df)
display(results.data)

display(results.calculator.previous_reference_results)

for metric in calc.metrics:
    figure = results.plot(kind='performance', plot_reference=True, metric=metric)
    figure.show()
```

**Expected behavior**
The plot would show date information just like it does in the [plot on the documentation](https://nannyml.readthedocs.io/en/stable/_images/tutorial-performance-calculation-regression-MAE.svg).

**Screenshots & scripts**
This is how the plot looks from the code provided.

![newplot(2)](https://user-images.githubusercontent.com/89025229/191721390-4d075280-2dc0-4493-95f5-8d4bab9822d3.png)

**Additional context**
Using version 0.6.2

**Comment by nnansters** [comment]
Already resolved on main, new release coming out today.
