### ISSUE TITLE
NannyML (quicstart code) silently fails to create a univariate drift plot when too many features are selected

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#169]
**Describe the bug**

When we have MANY features into univariate drift and use code trying to plot them all it fails silently. The machine still computes but does, presumably?, nothing.

**To Reproduce**

Posting example code since a full reproducible example relies on internal compute resources.

```

# load data and create reference and analysis dataframes
# in this cases fabert openml dataset

chunker = nml.SizeBasedChunker(chunk_size=_suggested_chunk_size)


univariate_calculator = nml.UnivariateDriftCalculator(
    column_names=feature_column_names,
    continuous_methods=['jensen_shannon'],
    categorical_methods=['jensen_shannon'],
    chunker=chunker,
)
univariate_calculator = univariate_calculator.fit(reference)
univariate_results = univariate_calculator.calculate(analysis)
```
In our case the selected features number is 800. Trying to create one plot with:

```
figure2 = univariate_results.filter(
    period='all',
    column_names=univariate_results.column_names, 
    methods=['jensen_shannon']).plot(kind='drift')
```
will fail and the Jupyterlab notebook kept running doing, presumably, nothing.

**Expected behavior**
A plot would be created.

**Additional context**
If instead we try to create plots one by one, things work fine:
```
for ftr in univariate_results.column_names:
    _fgr = univariate_results.filter(
        period='all',
        column_names=[ftr], 
        methods=['jensen_shannon']
    ).plot(kind='drift')
    _fgr.write_image(f"{_figure_folder}/drift-{ftr}.svg")
```

**Comment by nnansters** [comment]
Hey Nikos,

that seems like a very plausible scenario, I haven't been testing this for large numbers. We're currently relying on the "subplot" functionality of plotly for the "concatenation" of multiple plots. 
I found an alternative to this using PIL (Python Image Library), which might be more performant for that specific use case (and simplify the plotting methods). I'll give it a test, see if that resolves the issue.

In the worst case scenario we'll have to introduce a "hard limit" to the number of subplots and force the user to filter the results before plotting.

**Comment by nnansters** [comment]
The solution described above did not include the interactive plots, losing interactivity is too big a price to pay. 

For the time being, the solution to this will be looping over features (and optionally methods) when plotting. The `Result` object has multiple properties that allow you to loop over continuous, categorical or all column names in an easy way.

In the long term, we're looking at moving away from the "multiple methods at once" approach, which would eliminate this problem partially already.
