### ISSUE TITLE
Fix broken image link in documentation

### ISSUE THREAD

**Issue by jrggementiza** [NannyML/nannyml#173]
**Describe the bug**
There's a broken image link in the NannyML documentation

**To Reproduce**
1. [Click here to see the broken image link](https://github.com/NannyML/nannyml#1-performance-estimation-and-monitoring)
![brokenImageLink](https://user-images.githubusercontent.com/30363148/208726932-05c77cf7-50a3-4ce3-91e7-829c5a03a776.jpg) 

**Additional context**
- Based on the changes [here](https://github.com/NannyML/nannyml/pull/170/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L93), image name is in the wrong caps.

**Note**
- Trying my hand at contributing to open source. Feel free to disregard as needed.

**Comment by nnansters** [comment]
Good catch, thanks for your contribution!
