### ISSUE TITLE
Improve readability of sequence checking conditionals

### ISSUE THREAD

**Issue by jrggementiza** [NannyML/nannyml#175]
## Motivation
- Was poking around the codebase when I noticed sequence checking could use improvement in terms of code readability

## Solution
- We can use [Truth Value Testing](https://docs.python.org/3/library/stdtypes.html#truth-value-testing) in checking the truthy-ness of sequences to make it simpler

## Recommended Changes
- We can simplify the following code fragments:
```diff
- if len(some_sequence) > 0:
+ if some_sequence:
      do_something()
```
```diff
- if len(some_other_sequence) == 0:
+ if not some_other_sequence:
      do_something_else()
```

## Additional Context
- Caveat; have excluded the ones in `joy_plot.py` as those are numpy sequences and is a [different checking altogether](https://sopython.com/canon/119/the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous/)

## Note
Trying to make contributing to open source stick. Feel free to disregard.

**Comment by nnansters** [comment]
Nice improvement, cheers. Did not know about that syntax.
