### ISSUE TITLE
Align docstring and exception message to actual params in chunk module

### ISSUE THREAD

**Issue by jrggementiza** [NannyML/nannyml#177]
## Motivation
- Was reading the docs and found some inconsistencies in the example v actual implem params of count module

## Additional Context
![docstringVsParamsInCountBasedChunker](https://user-images.githubusercontent.com/30363148/211029859-7b1dbe0a-5431-4c76-bef2-963ec602ef58.jpg)
![docstringVsParamsInSizeBasedChunker](https://user-images.githubusercontent.com/30363148/211029864-8d030221-6298-49cf-a25c-4925c42582bb.jpg)

**Comment by nnansters** [comment]
Good catch! Cheers!
