### ISSUE TITLE
Make data-related error messages more specific

### ISSUE THREAD

**Issue by nnansters** [NannyML/nannyml#181]
**Motivation: describe the problem to be solved**

This issue was brought up by @bgalvao on the community Slack.

> In our case, the ground truth data that is arriving has no positive cases in a binary classification problem. It's all data filled with zeros!
> Our model did predict some positive cases, which resulted in
>
> ```
> CalculatorException: failed while calculating _BinaryClassificationCBPE.
> Classification metrics can't handle a mix of unknown and binary targets
> ```
> 
>
> Fair enough, the error message is specific. But I only understood it after inspecting y_true (all zeros) and y_pred (zeros and 1s). It could be nice to have more specific exceptions and have them documented in human language and examples that raise these specific exceptions. At least in this case, there could be an UnknownBinaryTargetException. Mind you, this could be me overthinking at this point. So either I inspect the data before running NannyML or I capture the error message. Ideally a try...except pattern would be nice :massage:

And also:

> Also, I noticed. I am using two metrics: roc_auc and specificity. If using roc_auc the message will be there are no positive cases in y_true. If using specificity, it will express itself as "mix of targets"

So in short:

Returning a "high level" NannyML exception that wraps a "low level" library exception (e.g. from scikit-learn) is bad because:

1. It fails to clearly communicate what is actually wrong
2. There might be different wrapped exceptions all pointing to the same root cause, making it more difficult for applications using NannyML to handle these wrapped exceptions in a proper way.

For example when some classes are not represented in target data when trying to calculate performance.  This would manifest in different exceptions being raised, depending on the kind of metric you're trying to calculate, but not a single one telling you you're missing some classes in your target data.

**Describe the solution you'd like**

We should introduce new exceptions that represent an "intermediate" level event, i.e. the true root cause.
These root causes might be checked explicitly within NannyML and be caught in advance. 

When an "unexpected" exception occurs somewhere after the explicit data checks have happened, we'll default to return the low level exception message (the current behavior).

There is no exhaustive list of exceptions to work from, so this will have to be a more "on demand" kind of improvement.
We can keep this issue open for some time and link to it from any new cases that might occur, e.g. the missing target data case.

**Comment by nnansters** [comment]
@bgalvao thoughts?

**Comment by bgalvao** [comment]
@nnansters I cannot think of anything else!

> When an "unexpected" exception occurs somewhere after the explicit data checks have happened, we'll default to return the low level exception message (the current behavior).

Is the best we can aim for.

I would perhaps add an exception for `MissingClassInReferenceData`? so that the user can adjust the chunking strategy, or wonder about the data spurcing strategy - just a random thought.
