### ISSUE TITLE
Document available options for 'magic strings' to select metrics, chunking, filtering

### ISSUE THREAD

**Issue by nnansters** [NannyML/nannyml#189]
**Motivation: describe the problem to be solved**

Right now you have to delve into the actual documentation pages to find what options are available for:

- Univariate drift methods
- Performance metrics
- Estimated performance metrics
- Chunking
- Filtering

These are not readily available in the docstrings and even in the documentation it is hard to find them (if they are there at all).

Reported by @PieDude12 

**Describe the solution you'd like**

For all of the places these values are used (mostly constructors) the values should be:

- Documented properly in the docstrings (parameter values & defaults + examples)
- Clearly listed in the reference API docs
- Clearly listed in tutorial pages

**Comment by michael-nml** [comment]
I'd suggest using python `Literal`'s as part of this solution. That should tackle the reference API docs and also provide auto-completion support when using the library.

I made a quick demo for the period filter. The code would be something like:

``` python
from typing_extensions import Literal

PeriodFilter = Literal['analysis', 'reference', 'all']

class Result:
    def filter(self, period: PeriodFilter = 'analysis', metrics: Optional[Union[str, List[str]]] = None, *args, **kwargs) -> Result:
        ...
```

Looks like this in the API docs:
![image](https://user-images.githubusercontent.com/124588413/217488667-3ad451b0-1dd1-4d7b-936a-3e044589e831.png)

And auto-complete in vscode looks like this:
![image](https://user-images.githubusercontent.com/124588413/217490131-c24711fb-f3c9-4bed-a6ba-0120405c302c.png)

I imagine PyCharm would provide a similar prompt, though I haven't tried.

**Comment by nnansters** [comment]
Ooh @michael-nml I did not know that. Very good suggestion! That should definitely be a part of the solution!
