### ISSUE TITLE
Issue with import nannyml on Kaggle

### ISSUE THREAD

**Issue by koo-ec** [NannyML/nannyml#190]
**Describe the bug**
I have tried to reimplement one of NannyML examples in Kaggle. and When I used the import command I got the following error.

import nannyml as nml
from IPython.display import display

**Expected behavior**

**Screenshots & scripts**
If applicable, add screenshots or code snippets to help explain your problem.
![image](https://user-images.githubusercontent.com/11271682/216089481-7a000b25-8736-4022-a6a0-697bd42b805e.png)

**Additional context**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_28/3486783819.py in <module>
----> 1 import nannyml as nml
      2 from IPython.display import display

/opt/conda/lib/python3.7/site-packages/nannyml/__init__.py in <module>
     49 from .drift import AlertCountRanker, CorrelationRanker, DataReconstructionDriftCalculator, UnivariateDriftCalculator
     50 from .exceptions import ChunkerException, InvalidArgumentsException, MissingMetadataException
---> 51 from .io import DatabaseWriter, PickleFileWriter, RawFilesWriter
     52 from .performance_calculation import PerformanceCalculator
     53 from .performance_estimation import CBPE, DLE

/opt/conda/lib/python3.7/site-packages/nannyml/io/__init__.py in <module>
      4 
      5 from .base import Reader, Writer, WriterFactory
----> 6 from .db import DatabaseWriter
      7 from .file_reader import FileReader
      8 from .file_writer import FileWriter

/opt/conda/lib/python3.7/site-packages/nannyml/io/db/__init__.py in <module>
      3 #  License: Apache Software License 2.0
      4 
----> 5 from .database_writer import DatabaseWriter

/opt/conda/lib/python3.7/site-packages/nannyml/io/db/database_writer.py in <module>
      1 from typing import Any, Dict, Optional
      2 
----> 3 from sqlmodel import Session, SQLModel, create_engine, select
      4 
      5 from nannyml._typing import Result

/opt/conda/lib/python3.7/site-packages/sqlmodel/__init__.py in <module>
    135 
    136 # Export SQLModel specifics (equivalent to Pydantic)
--> 137 from .main import SQLModel as SQLModel
    138 from .main import Field as Field
    139 from .main import Relationship as Relationship

/opt/conda/lib/python3.7/site-packages/sqlmodel/main.py in <module>
     24 )
     25 
---> 26 from pydantic import BaseConfig, BaseModel
     27 from pydantic.errors import ConfigError, DictError
     28 from pydantic.fields import SHAPE_SINGLETON

/opt/conda/lib/python3.7/site-packages/pydantic/__init__.cpython-37m-x86_64-linux-gnu.so in init pydantic.__init__()

/opt/conda/lib/python3.7/site-packages/pydantic/dataclasses.cpython-37m-x86_64-linux-gnu.so in init pydantic.dataclasses()

/opt/conda/lib/python3.7/site-packages/pydantic/main.cpython-37m-x86_64-linux-gnu.so in init pydantic.main()

TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

**Comment by nnansters** [comment]
Hey @koo-ec , 

there seems to have been some kind of breaking update in Pydantic recently, I found this referring to it: https://github.com/explosion/spaCy/issues/12034.

Could you check which version of Pydantic you have installed on that failing environment?
