### ISSUE TITLE
Inconsistent data periods due to filtering

### ISSUE THREAD

**Issue by nnansters** [NannyML/nannyml#197]
**Describe the bug**

When displaying univariate results I expect to see both reference and analysis. If I plot the results without a filter, that's exactly what I get. However, if I first filter by column_names, only analysis gets displayed:

![image](https://user-images.githubusercontent.com/94110348/216983899-b1a51c81-6ca8-4a6e-9f96-7a1d8534a4e2.png)

Reported by @WojtekNML 

**To Reproduce**
1. Create `UnivariateDriftCalculator`. Perform `fitting` and `calculating`
2. Plot results without filtering
3. Plot results with filtering on a column name

**Expected behavior**
Period 'behavior' is consistent.

**Comment by nnansters** [comment]
That seems to fix it indeed. Maybe add a test to verify? You shouldn't test the plotting, rather just look at the results data and verify it contains the correct periods

**Comment by michael-nml** [comment]
Good idea. I'll add that to this PR.

**Comment by michael-nml** [comment]
@nnansters Question on the preferred approach with tackling these test cases.

If my analysis is correct, we currently have 5 distinct `Result` implementations that all have a separate implementation of period filtering:

- Multivariate drift: `nannyml.drift.multivariate.data_reconstruction.Result`
- Univariate drift: `nannyml.drift.univariate.Result`
- Performance calculation: `nannyml.performance_calculation.Result`
- CBPE performance estimation: `nannyml.performance_estimation.confidence_based.Result`
- DLE performance estimation: `nannyml.performance_estimation.direct_loss_estimation.Result`

This issue affects all of them, so theoretically I'd add a test case for each of these. Or even multiple test cases, to verify the different values for the `period` argument. Alternatively, I could refactor the period filtering so there's a single implementation that will only require one set of test cases.

Could you advise which approach is preferred?

**Comment by nnansters** [comment]
Unifying the behavior might be possible up to a certain point, I think the best places to do that would be the `Abstract1DResult` and `Abstract2DResult` classes. You could then still customize the actual behavior in the implementing classes.  Do note that for the `Abstract2DResult` we currently only have the univariate drift result as an implementation. And, somewhat annoying, it doesn't have `metrics` but `methods` (terminology had to be correct). So you'll need a bit of a specific implementation there anyway. 

Kind of like that approach, might clean stuff up properly. Give it a try.

Concerning testing: I think filtering in all is still quite untested overall. It might make sense to add a couple of test scenarios. You could structure them in multiple ways but I think the easiest way would be to add the tests to each calculator module tests individually, and not have a `test_results.py` or such. Probably easier to reuse fixtures etc. that way.
