### ISSUE TITLE
Data requirements docs are incomplete for DLE

### ISSUE THREAD

**Issue by michael-nml** [NannyML/nannyml#212]
**Describe the bug**
The [data requirements documentation](https://nannyml.readthedocs.io/en/stable/tutorials/data_requirements.html#nannyml-functionality-requirements) is incomplete for DLE. Features is required, but listed as not necessary.

**Screenshots & scripts**
![image](https://user-images.githubusercontent.com/124588413/218433073-41eec140-2e3e-4504-95f8-bf2cf28297df.png)

**Additional context**
Perhaps CBPE and DLE should be listed separately given different requirements? E.g. the comment on `ROC_AUC` is relevant for CBPE, but not for DLE.

**Comment by nnansters** [comment]
Good spot!

Splitting them up is a good idea for the time being.

Want to tackle this one?

**Comment by michael-nml** [comment]
Sure, I'll prepare a draft. Review would be good though to make sure I don't miss anything 🙂
