### ISSUE TITLE
Multilevel table header in the docs not rendering properly.

### ISSUE THREAD

**Issue by jakubnml** [NannyML/nannyml#217]
What we see [in the docs:](https://nannyml.readthedocs.io/en/stable/tutorials/detecting_data_drift/univariate_drift_detection.html#)
![image](https://user-images.githubusercontent.com/100147443/219023428-a8840797-6d28-47f6-bd54-0fbc21d13277.png)

How it should look like:
![image](https://user-images.githubusercontent.com/100147443/219023086-1b1b4627-bf47-48f6-bf0c-e6ddac804f02.png)

I did quick research on my own but couldn't find how to fix that.

**Comment by alexnanny** [comment]
I took a look at this, and the problem is that is not easy to convert the multindex result to a table in rst.

I hacked a solution formatting the headers in a custom way. This is the result:
![CleanShot 2023-02-17 at 12 58 38](https://user-images.githubusercontent.com/124191512/219761853-cee9abe9-3123-4953-a27e-8816109cd957.png)

The custom formatting looks like this:

```python
visited = [[], []]
lines = []
for col in results.data.columns.values:
    line = ''

    top = col[0]
    top_not_visited = top not in visited[0]
    if top_not_visited:
        line += '| ' + top.strip()
        visited[0].append(top)
        visited[1] = []
    line += '\n'

    middle = col[1]
    middle_not_visited = middle not in visited[1]
    if middle_not_visited:
        line += '| ' + middle.strip()
        visited[1].append(middle)
    line += '\n'

    line += '| ' + col[2].strip()

    lines.append(line)

single_level_data = results.data.copy(deep=True)
single_level_data.columns = lines

print(single_level_data.to_markdown(tablefmt="grid", stralign='left', numalign='left' ))
```

This code makes the output of the headers look like this:

```
+---------------------+---------------------+-----------+------------------------+---------------------+---------------------+-----------+-------------------------+
|                     |                     |           |                        |                     |                     |           | | gas_price_per_litre   |
|                     |                     |           | | kolmogorov_smirnov   |                     |                     |           | | jensen_shannon        |
| | lower_threshold   | | upper_threshold   | | value   | | alert                | | lower_threshold   | | upper_threshold   | | value   | | alert                 |
+=====================+=====================+===========+========================+=====================+=====================+===========+=========================+
+---------------------+---------------------+-----------+------------------------+---------------------+---------------------+-----------+-------------------------+
```

@nnansters @nikml do you think is worth formatting that table this way? 

I feel it makes the docs look cleaner, at the expense of having a weird looking code on the notebook (instead of the usual `print(single_level_data.to_markdown(tablefmt="grid"`)

**Comment by nikml** [comment]
I like it, the weird looking code is not user facing so not that big of a problem. Assuming we could even make this a function somewhere? and import/call it when needed?

**Comment by alexnanny** [comment]
After a refactor we can have 2 functions:
```python
def format_multiindex_columns(df):
    size = len(df.columns.values[0])
    headers = []
    depths = list(range(0, size))
    visited = list(map(lambda _: [], depths))

    for col in df.columns.values:
        if isinstance(col, str):
            headers.append(col)
            continue

        header = ''
        for depth in depths:
            line = col[depth]
            is_visited = line in visited[depth]
            is_last_depth = depth == (len(depths) - 1)
            if not is_visited:
                header += '| ' + line.strip()
                visited[depth].append(line)
                if not is_last_depth:
                    visited[depth + 1] = []
                    header += '\n'
            else:
                header += '\n'

        headers.append(header)

    return headers

def format_multiindex_df(df):
    headers = format_multiindex_columns(df)
    single_level_data = df.copy(deep=True)
    single_level_data.columns = headers
    return single_level_data
```

This way we can use them to format df of N indexes

![CleanShot 2023-02-17 at 16 43 39](https://user-images.githubusercontent.com/124191512/219811872-233c34f0-10b6-4330-83c3-658ca73fd835.png)

Where should this functions live? is there another example of "docs only" functions?

**Comment by michael-nml** [comment]
Nice! Seems like a good solution 👍

Not sure about a place to store it though. I guess the easiest approach is to have to go inside the library, which seems like something we'd want to avoid. Alternatively we could store it under `docs` and add that directory to the path to enable imports. Manipulating `sys.path` could be done from `docs/run_notebooks.py`, but it would likely break running the notebook in an editor...

**Comment by nnansters** [comment]
Since this is formatting specifically for the docs I  prefer to have this be a part of the documentation build. This implies we should have a snippet of code that can take the formatted table as is and update the headers. Then we can make this a part of our custom directives we run to import notebook cells.

I'll give it a quick look
