### ISSUE TITLE
[DOCS] Columns description on results for estimated performance is outdated.

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#220]
Columns description for estimated performance is outdated.

Description:

![Screenshot 2023-02-17 at 14-53-41 Estimating Performance for Binary Classification — NannyML 0 8 3 documentation](https://user-images.githubusercontent.com/89025229/219658700-c32b8424-7867-4dc4-b5ac-91b480ab5c2e.png)

result index:
![Screenshot 2023-02-17 at 14-27-36 Tutorial%20-… - JupyterLab](https://user-images.githubusercontent.com/89025229/219658690-7dad3114-bd20-4662-b7ef-bbf9b2203419.png)

**Comment by nnansters** [comment]
Just noted that these were only updated for estimated binary performance.

Still lacking the updated version for:

- Estimated multiclass classification performance
- Estimated regression performance
- Realized binary classification performance
- Realized multiclass classification performance
- Realized regression performance
