### ISSUE TITLE
[DOCS] Performance Estimation plots no longer show realized on reference.

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#222]
As per title, docs need to be updated.

**Comment by nnansters** [comment]
Two options to deal with this:

1. Change the visualization to show realized performance for the reference period
2. Add a second line chart showing the realized performance (for reference and if available for analysis too)

1 is the old behavior, 2 is behavior that was discussed whilst refactoring plotting.

Opinions @BobbuAbadeer @PieDude12 @WojtekNML ?

**Comment by BobbuAbadeer** [comment]
I believe the intended behaviour for the library is to be clear that we're showing only estimated performance when you estimate performance, regardless of whether it's the reference or analysis period, so as Nik says, we just need to update the docs.
