### ISSUE TITLE
[Plotting] How to treat threshold for Chi2 drift detection?

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#234]
**Describe the bug**
Changes in [main](https://github.com/NannyML/nannyml/commits/main) have caused threshold to enter legend in Chi2 drift plots. But given that threshold for Chi2 is based on p-values - which are not plotted - this may confuse the user. Ideally we would not show this - as is the current `stable` behavior.

[Chi2 Drift results in latest.](https://nannyml.readthedocs.io/en/latest/_images/quick-start-drift-categorical.svg)

[Chi2 Drift results in stable.](https://nannyml.readthedocs.io/en/stable/_images/quick-start-drift-categorical.svg)

**Comment by michael-nml** [comment]
Discussed on Slack: decision is to not display the p-values threshold on the plot, so it should also not be displayed in the legend. This may be revised in future when considering custom thresholds in future.
