### ISSUE TITLE
Not able to Install nannyML in Mac M1 13.2 

### ISSUE THREAD

**Issue by gourav1298** [NannyML/nannyml#247]
* nannyml version: 0.8.3
* Python version: 3.9
* Operating System:Mac M1 Ventura 13.2

### Description

I am trying to install NannyMl in my Mac but I am facing an dependency issue

### What I Did
 ```
pip3 install nannyml

import nannyml as nml
```
```
Error:
ImportError: cannot import name 'LGBMClassifier' from 'flaml.default.estimator' (/Users/ggupta463/opt/anaconda3/lib/python3.9/site-packages/flaml/default/estimator.py)

```

**Comment by nnansters** [comment]
Hey @gourav1298 , 

this might be related to M1 compatibility issues.

Are you able to install `flaml` on its own? 

`pip3 install flaml`

You might have to set up some build dependencies  for local compilation first:

`brew install gcc
brew install CMake`
