### ISSUE TITLE
[Plotting] Inconsistent behavior of analysis period line

### ISSUE THREAD

**Issue by santiviquez** [NannyML/nannyml#262]
**Describe the bug**

Using version 0.8.4. Comparison plots show a **dashed** purple line for the analysis period, whereas, on performance estimation, they show a **solid** purple line.

Screenshot of analysis line displayed correctly (dashed):
![Screenshot 2023-03-23 at 16 45 38](https://user-images.githubusercontent.com/10890881/227271400-8164a7ee-dd36-40c1-9c88-313210ba8a8a.png)

Screenshot of analysis line displayed incorrectly (solid):
![Screenshot 2023-03-23 at 16 45 02](https://user-images.githubusercontent.com/10890881/227271447-729df0a4-c1d1-4069-b68f-6bea04cceb61.png)

**To Reproduce**
The [Tutorial - Estimating Standard Performance Metrics - Binary Classification](https://github.com/NannyML/nannyml/blob/main/docs/example_notebooks/Tutorial%20-%20Estimating%20Standard%20Performance%20Metrics%20-%20Binary%20Classification.ipynb) reproduces the error when plotting the results of CBPE.

**Expected behavior**
Show a purple **dashed** line for the reference period consistently across the comparison and performance estimation plots.

**Comment by nnansters** [comment]
Hey Santiago, 

dashed or solid lines are not an indicator of a data period (reference or analysis), but of an estimated (dotted) vs. calculated (solid) result. 
The line style is incorrect in the second plot however, both the reference and analysis period should be dotted lines.

This will soon be reinforced by the color scheme: purple lines indicate estimated results, blue lines indicate calculated results.

There is another issue (#261) about the legend, which is incorrect in the first (comparison) plot.
