### ISSUE TITLE
Performance calculator required parameters could be metrics dependent.

### ISSUE THREAD

**Issue by jakubnml** [NannyML/nannyml#265]
`nml.PerformanceCalculator` for `roc_auc ` metric requires `y_pred `parameter while it is not really needed for `roc_auc `(which needs only `y_true `and `y_pred_proba`).

![image](https://user-images.githubusercontent.com/100147443/228251951-9bd142d9-1dc0-4aca-924f-906b11092824.png)

**Comment by nnansters** [comment]
We could indeed check if we only need to calculate `roc_auc` then we could make `y_pred` optional. 

We'll have to add some docs as well to make the expectations clear, and also add a clear error message when it is not provided yet required.
