### ISSUE TITLE
Distribution plotting scaling done separately in reference and analysis.

### ISSUE THREAD

**Issue by jakubnml** [NannyML/nannyml#267]
Distribution plots are min-max scaled to nicely fill the horizontal space dedicated for each chunk. Here it seems that analysis and reference scaling is done separately which creates the illusion that distribution has changed between reference and first few chunks of analysis (became flat). 

![image](https://user-images.githubusercontent.com/100147443/228469539-29dd8f27-76d3-4ace-b9b2-b5b775340dde.png)

There are 2 possible solutions:
1. Scale everything together. Then all the distributions are comparable and closest to the true distribution. The issue is that if for one or more chunks we observe a strong peak (like in the plot) every other distribution would be very flat (like in most analysis chunks in the plot).
2. Scale every chunk separately - in that case every distribution fully fills the horizontal space dedicated for each chunk. The qualitative distribution comparison would be much easier - and that's the purpose of distribution plots. The weakness though is that frequency scales would be different for each chunk (I would say this is minor).

**Comment by nnansters** [comment]
Let's see if we can get option 2 implemented then.
