### ISSUE TITLE
Erroneous NaN result from some (regression realized) performance calculations

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#279]
**Describe the bug**
While working on an internal dataset the last chunk of data produced a `NaN` result for `mse` realized performance calculation.
Calculating the performance manually resulted in a valid performance value number.

The culprit appears to be [this line of code](https://github.com/NannyML/nannyml/blob/ec709becfdf52d0882bb8b720413417da6d62d0a/nannyml/performance_calculation/metrics/regression.py#L167). This check and it's treatment shouldn't be there.

We should also check if this behavior happens on other performance metrics.

**Comment by nnansters** [comment]
Pushed a quick fix for regression right now. We'll have to comb through the other metrics for a quick check if the same issue applies there.
