### ISSUE TITLE
JS Univariate Drift Incorrectly treating categorical as numerical

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#292]
**Describe the bug**
When a categorical column has many unique values it may be incorrectly treated as numerical. This may result in NaN drift values (unless unseen values are present in the relevant chunk).

This will happen with non numerical column types where the numerical part of the code will not work.

The recategorization causing the problem is this:
https://github.com/NannyML/nannyml/blob/ce4fc1802e9314e23352460a40e876de22ff5800/nannyml/drift/univariate/methods.py#L286-L287

**Comment by nnansters** [comment]
What would be a more correct way to approach this? Larger value for `n_unique_values`?

**Comment by nikml** [comment]
Not enforcing this checks on values that can't be converted to numeric, for example string postcode values, string US State values, etc.

There may be other edge cases that escape me but the above would capture the case that created this Issue.
