### ISSUE TITLE
Small visual bug in the plotting.

### ISSUE THREAD

**Issue by WojtekNML** [NannyML/nannyml#293]
**Describe the bug**
 If I fit and calculate multivariate drift (I suppose the same applies to all other calculators) on the same data, the reference and analysis plot subtitles overlap

**To Reproduce**
1. Generate data:
# Set the random seed for reproducibility
np.random.seed(0)

# Generate timestamp range
start_date = pd.Timestamp('2000-01-01')
end_date = pd.Timestamp('2023-12-31')
timestamps = pd.date_range(start=start_date, end=end_date, freq='D')

# Generate time series data with seasonalities and noise
seasonal_component = np.sin(2 * np.pi * np.arange(len(timestamps)) / 365)  # Seasonal component
noise = np.random.normal(loc=0, scale=0.2, size=len(timestamps))  # Noise component
time_series = 10 + seasonal_component + noise  # Combine seasonalities and noise

# Create the DataFrame
data = pd.DataFrame({'timestamp': timestamps, 'time_series': time_series})

data.to_csv('short.csv')

2. Run NannyML:
import pandas as pd
import nannyml as nml
# Load data from CSV file
data = pd.read_csv('short.csv') #1d data with timestamp
# Define feature columns
feature_column_names = [col for col in data.columns if col != 'timestamp']
# Instantiate drift calculator
calc = nml.DataReconstructionDriftCalculator(
    column_names=feature_column_names,
    timestamp_column_name='timestamp'
)
# Fit calculator on reference data
calc.fit(data)
# Calculate drift results on provided data
results = calc.calculate(data)
# Visualize results in a plot
figure = results.plot()
figure.show()

3. Plot:
![image](https://github.com/NannyML/nannyml/assets/100422459/ef232028-bdd0-4cb8-8395-fb1ae36191bb)

**Expected behavior**
Good question. 

Maybe the plot should be titled reference if same data is used to fit and calculate stuff?

**Comment by nnansters** [comment]
This will occur when the date / chunk index ranges for the data periods fully (or even partially) overlap. 

We could check the x-axis values for both and use that as a condition to plot the "annotation". It is maybe more correct to not plot any of the two annotations in that case?

**Comment by WojtekNML** [comment]
Ideally, I'd like to see it like this:
![image](https://github.com/NannyML/nannyml/assets/100422459/a3e2656d-239c-4850-bca6-e4ca1ce76c6b)
So that both of the periods are clearly indicated. No clue how easy/feasible something like that would be. Ofc this is just inspiration for how we could plot it. 

In the edge case of full overlap, I'd just call it either `reference` or `reference and analysis`. Maybe the latter?
