### ISSUE TITLE
Deafult chunker results in unequal chunk chunk across reference and analysis

### ISSUE THREAD

**Issue by WojtekNML** [NannyML/nannyml#300]
**Describe the bug**
Default chunking recalculates the number of chunks separate on reference and analysis, which leads to different chunk sizes in reference and analysis (if the size of the ref and analysis is not equal) 

**To Reproduce**
load 

n_rows = len(df)
split_index = int(n_rows * 0.7)

ref_data = df.iloc[:split_index]
analysis_data = df.iloc[split_index:]

column_names = ['time_series']
calc = UnivariateDriftCalculator(
    column_names=column_names,
    continuous_methods=['jensen_shannon'],
    categorical_methods=['jensen_shannon'],
    timestamp_column_name='timestamp',
).fit(ref_data)

**Expected behavior**
The default chunker should calculate the chunk size on reference and then apply that size to analysis, without recalculating the size of chunks. 

**Screenshots & scripts**
![image](https://github.com/NannyML/nannyml/assets/100422459/d7eb3851-5cac-4fc7-ae9a-5ae5796d1769)

**Additional context**
I would change the default chunking to size based with size = 1000

**Comment by jakubnml** [comment]
I'm not sure whether that's a bug. Being able to define a number of chunks on _analysis_ is useful. If you want to have fixed size of your chunk - use size-based chunker. If a user wants to have a fixed number of chunks - they use number-based chunking. 

I actually use number-based chunking a lot cause I often want to treat the whole analysis as a single chunk. 

@WojtekNML

**Comment by nnansters** [comment]
Hey,

using a separate chunker to handle reference and analysis data is certainly feasible. 

So suppose we introduce a second chunker. This means we'll have to prefix the existing parameter names with 'reference' or 'analysis' to make it clear which one we're specifying. E.g.

```
calc = UnivariateDriftCalculator(
  column_names=column_names,
  continuous_methods=['jensen_shannon'],
  categorical_methods=['jensen_shannon'],
  timestamp_column_name='timestamp',
  reference_chunk_size=1000,  # "preset" chunker for reference
  analysis_chunker=CountBasedChunker(chunk_count=10),   # "custom" chunker for analysis
).fit(ref_data)
```
This would mean breaking code compatibility; existing code no will no longer work.

As a fallback we might keep supporting the current syntax AS WELL, but have the given chunk settings apply to both the reference and analysis chunker. For example:

calc = UnivariateDriftCalculator(
  column_names=column_names,
  continuous_methods=['jensen_shannon'],
  categorical_methods=['jensen_shannon'],
  timestamp_column_name='timestamp',
  chunk_size=1000,   # both reference and analysis will be chunked using an instance of SizeBasedChunker
).fit(ref_data)
```

Something like this?

**Comment by WojtekNML** [comment]
At the first glance looks ok. Let's sleep on it. I'd potentially want the chunker for analysis to be specified during .calculate() maybe.  

For the time being, we should for sure change the default behavior.

**Comment by nnansters** [comment]
After sleeping on it (for a while) I do agree with the reasoning of @jakubnml :

> If you want to have fixed size of your chunk - use size-based chunker. If a user wants to have a fixed number of chunks - they use number-based chunking.

That being said, the current default behavior does look kind of weird. Current default is to split into 10 chunks, no matter the chunk size. We might make the default chunker more complex though, e.g. calculate the number of records so that the number of chunks on reference would be 10, then use that for a size based chunker?
That would ensure we have 10 reference chunks and a variable number of analysis chunks (of same "size").
