### ISSUE TITLE
Add DatabaseWriter support to `MissingValuesCalculator` and `UnseenValuesCalculator`

### ISSUE THREAD

**Issue by bgalvao** [NannyML/nannyml#313]
**Motivation: describe the problem to be solved**
The aforementioned calculators are a great addition to NannyML. However, for people looking to automate monitoring by writing to an SQL database and pulling those results, they are still not available.

**Describe the solution you'd like**
Enabling `DatabaseWriter.write()` on results from the aforementioned calculator. Ideally, it should be possible to write which values are unseen for monitoring on data that has not been preprocessed for model ingestion. Likewise, it should be possible to check which columns of the dataset have missing values from the `MissingValuesCalculator` result.

**Describe alternatives you've considered**
I do not think they exist in the open source yet ;)

**Additional context**

- [Slack conversation](https://nannymlbeta.slack.com/archives/C03LKV2N601/p1688026697337629?thread_ts=1687795900.323289&cid=C03LKV2N601).
- Need to be able to read this data from Grafana / Superset etc...

**Comment by bgalvao** [comment]
@nnansters I cannot add myself as assignee 😓

**Comment by santiviquez** [comment]
Hi @bgalvao, no worries. You can just comment here that you will work on this issue 😊

I saw that you opened a PR so that's great!
