### ISSUE TITLE
Standard Deviation stat failes on columns with only one value

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#330]
**Describe the bug**
When a column has only one value the standard deviation is 0. This causes summary_stats_std sampling error to fail (division by 0). Ideally we would fail gracefully (e.g. 0 sampling error value?) rather than error out.

**Comment by nnansters** [comment]
Tried reproducing but I don't succeed in triggering the division by zero:

```
def test_stats_std_calculator_should_not_fail_if_chunk_has_single_value():  # noqa: D103
    reference, analysis, _ = load_synthetic_car_loan_dataset()
    reference.loc[:, 'car_value'] = 1000
    try:
        calc = SummaryStatsStdCalculator(
            column_names=['car_value'],
        ).fit(reference)
        _ = calc.calculate(data=analysis)
    except Exception:
        pytest.fail()
```

Doing something wrong?

**Comment by nnansters** [comment]
This might be related to the fix we just made for Median in summary stats, to check.
