### ISSUE TITLE
Chunk Index inconsistency between hover and x-axis

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#351]
**Describe the bug**
The x-axis chunk index and the hover chunk index do not have the same numbers when plotting both reference and analysis. x-axis when using chunk_count (and other chunkers) without a timestamp column specified.

![Screenshot from 2024-01-12 13-48-48](https://github.com/NannyML/nannyml/assets/89025229/f39746c8-30eb-4116-836a-afb2af91b967)

**To Reproduce**
Run the following code sample with nannyml 0.10.1
```
import nannyml as nml
from IPython.display import display

reference_df, analysis_df, _ = nml.load_synthetic_car_loan_dataset()
display(reference_df.head())

column_names = ['car_value']

calc = nml.UnivariateDriftCalculator(
    column_names=column_names,
    treat_as_categorical=['y_pred'],
    continuous_methods=['jensen_shannon'],
    categorical_methods=['jensen_shannon'],
    chunk_number=6
)

calc.fit(reference_df)
results = calc.calculate(analysis_df)

figure = results.plot(kind='drift')
figure.show()
```

**Expected behavior**
Indexes will be consistent.

**Comment by nnansters** [comment]
Main idea here was that the "index" represents the number of the chunk in its respective dataset, i.e. reference and analysis. I'm not sure if that makes sense though, in the light of an "ever growing" analysis dataset and repeat NannyML runs...

Options for fixing this:

1. Check if we can use custom X-axis labels that show the chunk index according to the interpretation as listed above
2. Change the chunk index in the hover to match the one used for plotting on the X-axis.

What do you think is better?
