### ISSUE TITLE
Update to using pyarrow 14.0.0

### ISSUE THREAD

**Issue by amrit110** [NannyML/nannyml#365]
**Motivation: describe the problem to be solved**
Nannyml uses pyarrow (>=12.0.0,<13.0.0). 

**Describe the solution you'd like**
Update to using latest version of pyarrow (v0.15.0) which has several improvements or atleast v0.14.0

**Comment by amrit110** [comment]
Hi! @nnansters would this be a straightforward update? Can i attempt at submitting a PR?

**Comment by nnansters** [comment]
Hey @amrit110 , definitely. Just be aware that we need to maintain Python 3.7 support, which might require conditional imports. Like we did with numpy.

Thanks for looking into this, haven't had the time for it yet. Also our dependencies are in bad shape right now 😅

**Comment by amrit110** [comment]
Thanks @nnansters! Yeah, understand the pains of dependency management :). Have submitted a PR.
