### ISSUE TITLE
Confidence bounds on CBPE plot go above 1.0 when ROC-AUC is 1.0

### ISSUE THREAD

**Issue by hakimelakhrass** [NannyML/nannyml#41]
- nannyml version: 0.2.0

Description
The confidence bounds of the CBPE plot go above 1.0 when ROC-AUC is one. They should be cut off at 1.0 as a ROC-AUC of over 1.0 is impossible.

![image](https://user-images.githubusercontent.com/100148105/159008066-db11716a-2216-4b95-8212-112044984f73.png)

**Comment by nikml** [comment]
Has this been fixed with 0.3.0? @nnansters ?

**Comment by nnansters** [comment]
> Has this been fixed with 0.3.0? @nnansters ?

Nope, this one remains open for now. Seems like a good first issue for a contributor.

**Comment by rfrenoy** [comment]
Hi,

I have a few questions related to this issue:

* Is giving a confidence interval higher than 1 really considered a problem? I agree that it will never go above 1, however plotting an asymmetric confidence interval looks weird to me in this context.
* If fixing this behaviour is required, a way could be to change the `nannyml.plots._step_plot.py._plot_confidence_band` function and clip the `y` argument in the `go.Scatter` calls. However the best way to handle all possible metrics and the multiple range of values they can take is not so obvious and may require creating a dedicated `Metric` object. Moreover, adding this behaviour in a `plot` function looks to me like a break of the single-responsibility principle and should be handled separately. I am thinking of creating separated columns for lower and higher bounds in the `CBPEPerformanceEstimatorResult` object returned by the `estimate` function.

Any thoughts?

**Comment by nnansters** [comment]
Hi Rémy,

thank you for your insights once again!

I think there is an easy way to solve this that should respect the single-responsibility principle (ah, a reference to SOLID principles, well done!). 
The logical place to deal with this cropping/clipping would be during calculation. The value not exceeding 1 is not a plotting issue but a rule of the calculation really. 
The places where this is currently calculated are the `nannyml.performance_estimation_confidence_based._cbpe_binary_classification._calculate_confidence_deviations` and `nannyml.performance_estimation_confidence_based._cbpe_multiclass_classification._calculate_confidence_deviations` functions. Out of scope for this, but we'll soon be able to deduplicate these and move them back into the superclass.

By adding a `max` in there we should be able to limit the value to 1, that should prevent having to modify plotting or introducing bigger changes. 

What do you think?

**Comment by nnansters** [comment]
I also see where your remark on the dedicated `Metric` object is coming from. Regression metrics e.g. will not limit themselves to a max value of 1. Even stronger, they'll not have a max value at all. We've split up the CBPE implementations for different cases (binary classification, multiclass classficiation and soon regression) into separate subclasses of an abstract base class (sticking to the SOLID principles here), so any of the complications in dealing with the variation of metrics with bounded vs. unbounded confidence will be contained to a single class. The `_calculate_confidence_deviation` functions are just helpers, so we don't have to stick to a common interface. I think that would eliminate the explicit need for a full `Metric` object here.

On the contrary, we've already introduced it for performance calculation. We might just as well push the abstraction up a notch and repurpose those to also serve in performance estimation. 

For now, I would opt for keeping stuff simple. 

1. Fix classification cases by adding a `max` to the calculation of confidence deviation.
2. Deal with unbounded metrics for e.g. regression in the implementing subclass itself, not introducing too many new abstractions that might tie us down.
