### ISSUE TITLE
Optional dependency for database requirements

### ISSUE THREAD

**Issue by Duncan-Hunter** [NannyML/nannyml#412]
**Motivation: describe the problem to be solved**
The most recent version bumped up some requirements, specifically SQLAlchemy 2, which is a good thing and keeping dependencies up to date is important. However, it now forces me to migrate to SQLAlchemy 2 (which is something I should do), and install other database requirements, when it's not part of the library that I use. Something [similar is mentioned here](https://github.com/NannyML/nannyml/issues/331#issuecomment-1804704060).

**Describe the solution you'd like**
I'd like to add [optional dependencies](https://python-poetry.org/docs/pyproject/#extras) for the database module. As far as I can tell, it's only `sqlmodel` and maybe `psycopg2-binary` that would need an extra.

**Describe alternatives you've considered**
_just upgrading my internal SQLAlchemy library to handle version 2_, which is something on my todo list.

**Comment by Duncan-Hunter** [comment]
And can I also tack on updating the s3fs requirement, as it limits it to versions before 2023, which is kind of putting me in versioning hell

**Comment by nnansters** [comment]
Closed thanks to the wonderful contribution of @Duncan-Hunter !
