### ISSUE TITLE
Need to update nannyml rich version to support >=13.0.0

### ISSUE THREAD

**Issue by llFireHawkll** [NannyML/nannyml#420]
Facing compattiblity issues when installing with evidently latest tag release.

**Comment by llFireHawkll** [comment]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/ed042181-6df4-4419-819a-aa3e5b3b2470">

**Comment by llFireHawkll** [comment]
@nnansters Can you please help update the dependency?

**Comment by nnansters** [comment]
Should be fixed in our brand new 0.12.0 release!

**Comment by llFireHawkll** [comment]
Great! Thanks @nnansters looking forward to the release.

**Comment by nnansters** [comment]
You can try it right now!
