### ISSUE TITLE
Can't load dataset

### ISSUE THREAD

**Issue by nlp-sid** [NannyML/nannyml#73]
* nannyml version: 0.4.0
* Python version: 3.8.0
* Operating System: 5.10.102.1-microsoft-standard-WSL2 ; Ubuntu 18.04.6 LTS

### Description

I'm trying to walk through the Quickstart guide and getting the following error:
module 'nannyml' has no attribute 'load_synthetic_binary_classification_dataset'

### What I Did

```
import pandas as pd
import nannyml as nml
from IPython.display import display
reference, analysis, analysis_target =nml.load_synthetic_binary_classification_dataset()
display(analysis.head())
display(reference.head())
```

**Comment by nikml** [comment]
This is very strange. Usually this error is present when someone tries to run an older version of the library like in #71 

Do you mind double checking the nannyml version with:

```
import nannyml as nml
print(nml.__version__)
```

**Comment by nlp-sid** [comment]
I get: 

import nannyml as nml
print(nml.__version__)

Output: AttributeError: module 'nannyml' has no attribute '__version__'


If I test with something like pandas it works correctly:
import pandas as pd
print(pd.__version__)
Output: 1.4.1

Though, if I run pip freeze I see it listed: nannyml==0.4.0

pip show nannyml gives me:
Name: nannyml
Version: 0.4.0
etc...

**Comment by nlp-sid** [comment]
I ran dir(nml) and got the following output:
['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

...so I think that's why the version attribute doesn't work.

At any rate, I ran the recommended and this is the output:

pip install --upgrade --force-reinstall nannyml                 
                                                                                                                               
Defaulting to user installation because normal site-packages is not writeable
Collecting nannyml
  Using cached nannyml-0.4.0-py3-none-any.whl (9.5 MB)
Collecting plotly<6.0.0,>=5.6.0
  Using cached plotly-5.8.0-py2.py3-none-any.whl (15.2 MB)
Collecting types-python-dateutil<3.0.0,>=2.8.9
  Using cached types_python_dateutil-2.8.15-py3-none-any.whl (7.9 kB)
Collecting offset<0.0.3,>=0.0.2
  Using cached offset-0.0.2-py3-none-any.whl (4.7 kB)
Collecting matplotlib<4.0.0,>=3.5.1
  Using cached matplotlib-3.5.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
Collecting python-dateutil<3.0.0,>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting seaborn<0.12.0,>=0.11.2
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting joblib<2.0.0,>=1.1.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting scikit-learn<2.0.0,>=1.0.2
  Using cached scikit_learn-1.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.0 MB)
Collecting category-encoders<3.0.0,>=2.3.0
  Using cached category_encoders-2.4.1-py2.py3-none-any.whl (80 kB)
Collecting pandas<2.0.0,>=1.3.0
  Using cached pandas-1.4.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting scipy<1.8.0,>=1.7.3
  Using cached scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
Collecting statsmodels>=0.9.0
  Using cached statsmodels-0.13.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.9 MB)
Collecting numpy>=1.14.0
  Using cached numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting patsy>=0.5.1
  Using cached patsy-0.5.2-py2.py3-none-any.whl (233 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-9.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting tenacity>=6.2.0
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Installing collected packages: types-python-dateutil, pytz, threadpoolctl, tenacity, six, pyparsing, pillow, offset, numpy, kiwisolver, joblib, fonttools, cycler, scipy, python-dateutil, plotly, patsy, packaging, scikit-learn, pandas, matplotlib, statsmodels, seaborn, category-encoders, nannyml
  Attempting uninstall: types-python-dateutil
    Found existing installation: types-python-dateutil 2.8.15
    Uninstalling types-python-dateutil-2.8.15:
      Successfully uninstalled types-python-dateutil-2.8.15
  Attempting uninstall: pytz
    Found existing installation: pytz 2022.1
    Uninstalling pytz-2022.1:
      Successfully uninstalled pytz-2022.1
  Attempting uninstall: threadpoolctl
    Found existing installation: threadpoolctl 3.1.0
    Uninstalling threadpoolctl-3.1.0:
      Successfully uninstalled threadpoolctl-3.1.0
  Attempting uninstall: tenacity
    Found existing installation: tenacity 8.0.1
    Uninstalling tenacity-8.0.1:
      Successfully uninstalled tenacity-8.0.1
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.0.9
    Uninstalling pyparsing-3.0.9:
      Successfully uninstalled pyparsing-3.0.9
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.1.0
    Uninstalling Pillow-9.1.0:
      Successfully uninstalled Pillow-9.1.0
  Attempting uninstall: offset
    Found existing installation: offset 0.0.2
    Uninstalling offset-0.0.2:
      Successfully uninstalled offset-0.0.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.3
    Uninstalling numpy-1.22.3:
      Successfully uninstalled numpy-1.22.3
  Attempting uninstall: kiwisolver
    Found existing installation: kiwisolver 1.4.2
    Uninstalling kiwisolver-1.4.2:
      Successfully uninstalled kiwisolver-1.4.2
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: fonttools
    Found existing installation: fonttools 4.33.3
    Uninstalling fonttools-4.33.3:
      Successfully uninstalled fonttools-4.33.3
  Attempting uninstall: cycler
    Found existing installation: cycler 0.11.0
    Uninstalling cycler-0.11.0:
      Successfully uninstalled cycler-0.11.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scipy-1.7.3:
      Successfully uninstalled scipy-1.7.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
      Successfully uninstalled python-dateutil-2.8.2
  Attempting uninstall: plotly
    Found existing installation: plotly 5.8.0
    Uninstalling plotly-5.8.0:
      Successfully uninstalled plotly-5.8.0
  Attempting uninstall: patsy
    Found existing installation: patsy 0.5.2
    Uninstalling patsy-0.5.2:
      Successfully uninstalled patsy-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.1.0
    Uninstalling scikit-learn-1.1.0:
      Successfully uninstalled scikit-learn-1.1.0
  Attempting uninstall: pandas
    Found existing installation: pandas 1.4.2
    Uninstalling pandas-1.4.2:
      Successfully uninstalled pandas-1.4.2
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.2
    Uninstalling matplotlib-3.5.2:
      Successfully uninstalled matplotlib-3.5.2
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.13.2
    Uninstalling statsmodels-0.13.2:
      Successfully uninstalled statsmodels-0.13.2
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.11.2
    Uninstalling seaborn-0.11.2:
      Successfully uninstalled seaborn-0.11.2
  Attempting uninstall: category-encoders
    Found existing installation: category-encoders 2.4.1
    Uninstalling category-encoders-2.4.1:
      Successfully uninstalled category-encoders-2.4.1
  Attempting uninstall: nannyml
    Found existing installation: nannyml 0.4.0
    Uninstalling nannyml-0.4.0:
      Successfully uninstalled nannyml-0.4.0
Successfully installed category-encoders-2.4.1 cycler-0.11.0 fonttools-4.33.3 joblib-1.1.0 kiwisolver-1.4.2 matplotlib-3.5.2 nannyml-0.4.0 numpy-1.22.3 offset-0.0.2 packaging-21.3 pandas-1.4.2 patsy-0.5.2 pillow-9.1.0 plotly-5.8.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.1 scikit-learn-1.1.0 scipy-1.7.3 seaborn-0.11.2 six-1.16.0 statsmodels-0.13.2 tenacity-8.0.1 threadpoolctl-3.1.0 types-python-dateutil-2.8.15








If I think rerun the same thing I get the same issue:

import pandas as pd
import nannyml as nml
from IPython.display import display
reference, analysis, analysis_target = nml.load_synthetic_binary_classification_dataset()
display(analysis.head())
display(reference.head())


AttributeError: module 'nannyml' has no attribute 'load_synthetic_binary_classification_dataset'

**Comment by nlp-sid** [comment]
pip 22.1

**Comment by nikml** [comment]
!? Something is really off. I don't know what else to ask but from what you are saying it looks like the library is not installing properly. i m saying this based on the `dir(nml)` output you have provided. I tried but can't reproduce the problem you are seeing.

**Comment by nlp-sid** [comment]
FWIW, my co-worker was able to load it just fine (he's on Python 3.7). I tried using a virtual environment but get the same issue. I've never seen something like this, so I'm at a loss. Worst case I may just re-image the hard drive. Thanks though!

**Comment by nlp-sid** [comment]
I re-created the virtual environment with what I believe to be the same steps from this morning and it now works correctly. I think my machine may just be haunted. Thanks again!

**Comment by nikml** [comment]
Nice to see that you were able to sort this out!

It's amazing how often doing something from scratch in computers fixes a problem. Maybe there are [ghosts in the machine](https://www.reddit.com/r/HFY/comments/bp97iv/a_ghost_in_the_machine_prologue/) ;)
