### ISSUE TITLE
Metadata-extraction documentation link 'Failed to open page'

### ISSUE THREAD

**Issue by SoyGema** [NannyML/nannyml#76]
* nannyml version: 0.4.1
* Python version: 3.7
* Operating System: Mac

### Description

Fit the CBPE .
Metadata is missing values 
It raised an error ['partition_column_name'] .
 I'm not assigning the partition column , as it appears labeled with  ~ UNKNOWN ~

### What I Did

```
cbpe_auto.fit(reference_data=reference)
```

### Backtrace

MissingMetadataException: metadata is still missing values for ['partition_column_name'].
Please rectify by renaming columns following automated extraction conventions
and re-running preprocessing or set metadata properties manually.
See https://docs.nannyml.com/metadata-extraction for more information

Beyond the error for fitting CBPE (fixed) , the **issue** comes from the **broken link** that the backtrace error raises , as I tried to follow the documentation link for more information, but It failed to open page.

**Comment by nikml** [comment]
Hello @SoyGema 
The correct link should be
https://nannyml.readthedocs.io/en/main/how_it_works/metadata_extraction.html

Good attention to detail, we 'll be addressing this in the next documentation updates.
