### ISSUE TITLE
Example plots not showing

### ISSUE THREAD

**Issue by IgnacioPascale** [NannyML/nannyml#90]
* nannyml version: 0.4.1/ 0.4.0
* Python version: python:3.8
* Operating System: [python:3.8-slim-bullseye Docker image](https://hub.docker.com/layers/python/library/python/3.8-slim-bullseye/images/sha256-0e67fbf9922ce0c49dfa23f790c25f555a074f0d293108034901213d48967d1d?context=explore) (Debian based)

### Description

I was trying to reproduce the example on the main readme. Plots are not showing. See below:

![image](https://user-images.githubusercontent.com/50626626/173315035-3894737d-790f-4183-8371-16436117e6aa.png)

![image](https://user-images.githubusercontent.com/50626626/173315087-ce21350d-a3a7-4fc0-a396-c8f9c29dc59b.png)

I tried this with both versions 0.4.0/0.4.1

If it helps, I'm using:

```
jupyterlab==3.4.2
pandas==1.4.1
```

### What I Did

Example on readme, as is:

```python
import pandas as pd
import nannyml as nml

# Load synthetic data
reference, analysis, analysis_target = nml.load_synthetic_binary_classification_dataset()
data = pd.concat([reference, analysis], ignore_index=True)

# Extract meta data
metadata = nml.extract_metadata(data = reference, model_name='wfh_predictor', model_type='classification_binary', exclude_columns=['identifier'])
metadata.target_column_name = 'work_home_actual'

# Choose a chunker or set a chunk size
chunk_size = 5000

# Estimate model performance
estimator = nml.CBPE(model_metadata=metadata, metrics=['roc_auc'], chunk_size=chunk_size)
estimator.fit(reference)
estimated_performance = estimator.estimate(data=data)

figure = estimated_performance.plot(metric='roc_auc', kind='performance')
figure.show()

# Detect multivariate feature drift
multivariate_calculator = nml.DataReconstructionDriftCalculator(model_metadata=metadata, chunk_size=chunk_size)
multivariate_calculator.fit(reference_data=reference)
multivariate_results = multivariate_calculator.calculate(data=data)

figure = multivariate_results.plot(kind='drift')
figure.show()

# Detect univariate feature drift
univariate_calculator = nml.UnivariateStatisticalDriftCalculator(model_metadata=metadata, chunk_size=chunk_size)
univariate_calculator.fit(reference_data=reference)
univariate_results = univariate_calculator.calculate(data=data)

# Rank features based on number of alerts
ranker = nml.Ranker.by('alert_count')
ranked_features = ranker.rank(univariate_results, model_metadata=metadata, only_drifting = False)

for feature in ranked_features.feature:
    figure = univariate_results.plot(kind='feature_distribution', feature_label=feature)
    figure.show()
```

Thank you!

**Comment by nikml** [comment]
This looks like a plotly issue:

Can you check if the code sample below from [plotly documentation](https://plotly.com/python/figure-structure/) works:

```
import plotly.express as px

fig = px.line(x=["a","b","c"], y=[1,3,2], title="sample figure")
print(fig)
fig.show()
```

**Comment by nnansters** [comment]
Hi @IgnacioPascale , thanks for logging this issue (and trying NannyML obviously).

I recall us sometimes bumping into this in some external environments. Installing the `jupyterlab-plotly` extension helped out in those cases.

Run the following as your first cell in your notebook:

`!jupyter labextension install jupyterlab-plotly`.

Hope that resolves your issue!

**Comment by nnansters** [comment]
Hmm, be sure to restart your notebook kernel AND do a hard refresh of your browser, maybe run in an incognito browser to be sure. This is required to see the effects of installing the `jupyterlab-plotly` extension.

**Comment by IgnacioPascale** [comment]
Thanks @nnansters! I had tried restarting the notebook kernel many times as I knew it was an issue, but hadn't tried running on incognito. The latter worked. Thank you!

**Comment by nnansters** [comment]
Awesome! Browsers are weird.

Enjoy the library!
