### ISSUE TITLE
kind parameter of plot(...) returns incorrect options in error message

### ISSUE THREAD

**Issue by YYYasin19** [NannyML/nannyml#94]
**Describe the bug**
The `plot` function in [multivariate data drift detection](https://github.com/NannyML/nannyml/blob/0df7df345e0b6fecff0e0ef1fea106c3a0f7bb77/nannyml/drift/model_inputs/multivariate/data_reconstruction/results.py#L85) takes an argument `kind:str` which can only be `drift` but the error message provides different / wrong options.

**To Reproduce**
Call `.plot(kind='feature_drift')` on the result of a `DataReconstructionDriftCalculator`

**Expected behavior**
Error message should include correct options for the plots _and_ accept `feature_drift` instead of just `drift` to be more inline with other options.

**Additional context**

Would be happy to create a quick PR fixing the issue :-)

**Comment by nikml** [comment]
Nice catch @YYYasin19 
We 'll fix it, unless you want to make a PR for it yourself?

**Comment by YYYasin19** [comment]
Thanks for responding so fast!
